// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAL2NFFrZz8HeDTeGHKFicxPNNPJfoHxnI',
    appId: '1:1015682323471:ios:6a6f080574b320083bff7a',
    messagingSenderId: '1015682323471',
    projectId: 'course-project-a99de',
    storageBucket: 'course-project-a99de.appspot.com',
    iosBundleId: 'com.example.ecommerce',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAL2NFFrZz8HeDTeGHKFicxPNNPJfoHxnI',
    appId: '1:1015682323471:ios:6a6f080574b320083bff7a',
    messagingSenderId: '1015682323471',
    projectId: 'course-project-a99de',
    storageBucket: 'course-project-a99de.appspot.com',
    iosBundleId: 'com.example.ecommerce',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCRCu8sK5r2B69-n-L9iO8Jd0PVmumyNQI',
    appId: '1:1015682323471:web:7ecd0c88666ec1743bff7a',
    messagingSenderId: '1015682323471',
    projectId: 'course-project-a99de',
    authDomain: 'course-project-a99de.firebaseapp.com',
    storageBucket: 'course-project-a99de.appspot.com',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCRCu8sK5r2B69-n-L9iO8Jd0PVmumyNQI',
    appId: '1:1015682323471:web:7ecd0c88666ec1743bff7a',
    messagingSenderId: '1015682323471',
    projectId: 'course-project-a99de',
    authDomain: 'course-project-a99de.firebaseapp.com',
    storageBucket: 'course-project-a99de.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_uRTlWuW4E8ZSC8riljRD3yDedDJ414U',
    appId: '1:1015682323471:android:c82c5001b4846ebc3bff7a',
    messagingSenderId: '1015682323471',
    projectId: 'course-project-a99de',
    storageBucket: 'course-project-a99de.appspot.com',
  );

}